spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentFallback
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
          filters:
            - name: CircuitBreaker
              args:
                name: EMPLOYEE-SERVICE
                fallbackuri: forward:/employeeFallback

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000